# Generated by Django 5.0.6 on 2024-06-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(blank=True, to='recipes.recipe', verbose_name='список избранного'),
        ),
        migrations.AddField(
            model_name='user',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='users', to='recipes.recipe', verbose_name='корзина покупок'),
        ),
    ]
