# Generated by Django 5.0.6 on 2024-07-10 17:28

import django.core.validators
from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Не корректное имя пользователя', regex='[\\w.@+-]+'), users.validators.validate_name], verbose_name='никнэйм'),
        ),
    ]
