# Generated by Django 5.0.6 on 2024-07-07 17:35

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Не корректное имя пользователя', regex='^[w.@+-]+Z'), users.validators.validate_name], verbose_name='никнэйм'),
        ),
    ]
