# Generated by Django 5.0.6 on 2024-07-11 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shopping_cart',
        ),
    ]
