# Generated by Django 5.0.6 on 2024-07-19 13:35

import django.core.validators
from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_follow_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('following__username',), 'verbose_name': 'Подписка'},
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Не корректное имя пользователя', regex='^[\\w.@+-]+$'), users.validators.validate_name], verbose_name='никнэйм'),
        ),
    ]
